version: 2.1

jobs:
  setup-and-test:
    docker:
     - image: circleci/python:3.8

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          
      - run:
          name: Install Dependencies
          command: pip install requirements.txt

      - run:
          name: Run Tests
          command: pytest test_sparse_recommender.py

      - run:
          name: Build Docker Image
          command: |
            docker build -t "$DOCKER_USERNAME"/sparse:"${CIRCLE_SHA1}" .

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKER_Password" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "$DOCKER_USERNAME"/sparse:"${CIRCLE_SHA1}"


workflows:
  Setup_and_Test:
    jobs:
      - setup-and-test